export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

//Topic
export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

//User
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

//Fiche
export const GET_FICHES = 'GET_FICHES';
export const GET_FICHES_REQUEST = 'GET_FICHES_REQUEST';
export const GET_FICHES_SUCCESS = 'GET_FICHES_SUCCESS';
export const GET_FICHES_FAILURE = 'GET_FICHES_FAILURE';
export const CREATE_FICHE_REQUEST = 'CREATE_FICHES_REQUEST';
export const CREATE_FICHE_FAILURE = 'CREATE_FICHES_FAILURE';
export const CREATE_FICHE_SUCCESS = 'CREATE_FICHES_SUCCESS';
export const CREATE_FICHE_DUPLICATE = 'CREATE_FICHES_DUPLICATE';
export const FICHE_TYPING = 'FICHE_TYPING';
export const DESTROY_FICHE = 'DESTROY_FICHE';
export const EDIT_FICHE_SUCCESS = 'EDIT_FICHE';
export const EDIT_FICHE_FAILURE='EDIT_FICHE_FAILURE';

//Playlist
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLISTS_REQUEST = 'GET_PLAYLISTS_REQUEST';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAILURE = 'GET_PLAYLISTS_FAILURE';

//Formulaire

export const SUBMIT_FORM = 'SUBMIT_FORM';